name: Build firmware
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install gcc-arm-none-eabi 
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: thumbv7m-none-eabi
            profile: minimal

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: stm32f1-modbus-test.elf
          path: target/thumbv7m-none-eabi/release/stm32f1-modbus-test
          if-no-files-found: error
