name: Build firmware
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install gcc-arm-none-eabi 
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: thumbv7m-none-eabi
            profile: minimal

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          cargo build --release
          arm-none-eabi-objcopy -O ihex target/thumbv7m-none-eabi/release/ext-quartz-8mhz ext-quartz-8mhz.hex
          arm-none-eabi-objcopy -O ihex target/thumbv7m-none-eabi/release/int-resonator int-resonator.hex

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Executables (iHex)
          path: |
            ext-quartz-8mhz.hex
            int-resonator.hex
          if-no-files-found: error
